apiVersion: v1
kind: Secret
metadata:
  name: assignment1
  namespace: vetoki
type: Opaque
stringData:
  DATABASE_URL: "postgresql://vetoki:vetoki@postgres-postgresql.db.svc.cluster.local:5432/vetoki"
