apiVersion: v1
kind: Service
metadata:
  name: assignment1-app
  namespace: vetoki
spec:
  # Choose the appropriate service type (ClusterIP is recommended for this setup)
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: assignment1-app
