apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assignment2-ingress
  namespace: vetoki
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns01"
    external-dns.alpha.kubernetes.io/hostname: "vetoki.a2.kumpan.btlc.dev"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - vetoki.a2.kumpan.btlc.dev
    secretName: assignment2-tls
  rules:
  - host: vetoki.a2.kumpan.btlc.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: assignment2-service
            port:
              number: 80
