apiVersion: v1
kind: Secret
metadata:
  name: assignment2-secret
  namespace: vetoki
type: Opaque
stringData:
  DATABASE_URL: "postgresql://vetoki:vetoki@postgres-postgresql.db.svc.cluster.local/public"
